import { createServiceClient } from '@/lib/supabase'
import { NextRequest } from 'next/server'

// Weekly digest — pure DB read, no LLM.
// Returns the top articles from the last 7 days with enriched fields
// (why_it_matters, key_takeaways) generated by the pipeline at crawl time.
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const userId = searchParams.get('userId') || process.env.NEXT_PUBLIC_USER_ID!
  const days = parseInt(searchParams.get('days') || '7', 10)

  const from = new Date()
  from.setDate(from.getDate() - days)
  const fromISO = from.toISOString().split('T')[0]

  try {
    const db = createServiceClient()
    const { data } = await db
      .from('user_feed_items')
      .select('blend_score, feed_date, articles(id, url, title, tldr_bullets, topic_tags, why_it_matters, key_takeaways, published_at)')
      .eq('user_id', userId)
      .gte('feed_date', fromISO)
      .order('blend_score', { ascending: false })
      .limit(30)

    if (!data || data.length === 0) {
      return Response.json({ items: [] })
    }

    const items = data
      .map((item: Record<string, unknown>) => {
        const art = Array.isArray(item.articles) ? item.articles[0] : item.articles as Record<string, unknown> | null
        if (!art) return null
        return {
          id: art.id,
          url: art.url,
          title: art.title,
          blend_score: item.blend_score,
          feed_date: item.feed_date,
          topic_tags: Array.isArray(art.topic_tags) ? art.topic_tags : [],
          tldr_bullets: Array.isArray(art.tldr_bullets) ? art.tldr_bullets : [],
          why_it_matters: art.why_it_matters ?? null,
          key_takeaways: Array.isArray(art.key_takeaways) ? art.key_takeaways : [],
          published_at: art.published_at ?? null,
        }
      })
      .filter(Boolean)

    return Response.json({ items })
  } catch (err) {
    return Response.json({ items: [], error: String(err) })
  }
}
